# Main settings
FPS = 60
SCALE_FACTOR = 2
TILE = 32 * SCALE_FACTOR
SIZE = WIDTH, HEIGHT = TILE * 12, TILE * 12
ANIM_FRAME_DURATION = 10
PLAYER_SIZE = 3
PLAYER_SPEED = TILE * 5
# Map Layerss
COLLISION_LAYER = 0
PLAYER_LAYER = 3
# Colors
BACKGROUND_COLOR = (6, 6, 8)
