# Main settings
FPS = 60
SCALE_FACTOR = 2
UNSCALE_TILE = 32
TILE = UNSCALE_TILE * SCALE_FACTOR
SIZE = WIDTH, HEIGHT = UNSCALE_TILE * 24, UNSCALE_TILE * 24
ANIM_FRAME_DURATION = 10
PLAYER_SIZE = 3
PLAYER_SPEED = TILE * 5
# Map Layers
COLLISION_LAYER = 0
